### PR TITLE
Add OXT ERC-20 Token

### PR DESCRIPTION
**Pull request by nhandler**
Add Orchid's OXT ERC-20 Token.

### CODE REVIEW

**Comment by nhandler** [comment]
Just in case the GitHub re-review request didn't actually trigger a notification, I wanted to note that I moved the new file to the tokens directory as requested.

**Comment by jspence425** [comment]
Hey @ligi - just pinging to take another look!

Kind regards,
Jordan

**Comment by ligi** [comment]
Thanks for the ping @jspence425 - unfortunately this one slipped through the cracks

**Comment by nhandler** [comment]
I've fixed the token addresses to be in ERC-55, @ligi . Interestingly, It looks like #309 also added a minimal version of the token. However, this PR includes much more detail, so it still appears relevant.

**Pull request merged**
