### PR TITLE
Added DEEZ Token to Defaults

### PR DESCRIPTION
**Pull request by DeezNutsToken**

### CODE REVIEW

**Comment by DeezNutsToken** [comment]
Thanks @ligi. Trust wallet wanted all lower-case, so I figured it made things easier. Will fix this up.

Do you mean the address in the filename, or the field in the json?

**Comment by ligi** [comment]
Thanks! Really wonder why trust wants it in lower-case and not ERC-55 (cc @vikmeup ) - I think using a checksum here is important to prevent typos and such

**Comment by vikmeup** [comment]
@ligi yes, you are right! Let me change to ERC55. Do you have a script by any chance to rename all the files in this repo: https://github.com/TrustWallet/tokens/tree/master/images? 

Otherwise will take a look tomorrow

**Comment by ligi** [comment]
@vikmeup great! I do not have this exact script but can make it with a small modification of my scripts - will PR it later for you - just have to finish one other thing - thanks for responding so fast!

**Comment by ligi** [comment]
Thanks for the quick fix!

**Pull request merged**
