### PR TITLE
Create 0xfb11D7ffdE8D643F5368C62fA9943BceaBcB0c36.json

### PR DESCRIPTION
**Pull request by TheGooseCoin**
Add GOOSE token

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
seems there is no contract deployed at 0xfb11D7ffdE8D643F5368C62fA9943BceaBcB0c36

**Comment by MrLightspeed** [comment]
> 

This is a BEP-20 Token - is it supported?
https://bscscan.com/token/0xfb11d7ffde8d643f5368c62fa9943bceabcb0c36

**Comment by MrLightspeed** [comment]
Can confirm that decimals is supposed to be (2)

**Comment by MrLightspeed** [comment]
json updated to BEP20

**Comment by ligi** [comment]
you would need to put your token in a folder called bsc - not in eth - but bsc is untested - can't guarantee it works - and myself have no interest in this chain ..

**Pull request closed without merging**
