### PR TITLE
added token info for fake RBT token

### PR DESCRIPTION
**Pull request by realola**
Adding RBT token info for a fake RealtyBits token issued on the Uniswap V2 protocol.

### CODE REVIEW

**Comment by realola** [comment]
This token is issued using our company name (RealtyBits) which is trademarked name. It is used without our authorization and is fraudulent. RealtyBits does not currently have any issued ERC-20 tokens.

**Comment by ligi** [comment]
thanks for the PR - can you rebase to master? The support for the suspicious field must be in before - just merged it

**Comment by realola** [comment]
Thanks, just rebased to master.

**Comment by ligi** [comment]
Thanks - but seems github has a problem currently - the diff does not make sense currently. Maybe we need to wait a bit.

**Comment by ligi** [comment]
If you need it faster it might make sense to close this one and open another one. Not sure how to trigger github so we get a clean diff

**Comment by realola** [comment]
Closing this one and creating a new one

**Comment by realola** [comment]
Here is a link to the new PR with a clean diff: https://github.com/ethereum-lists/tokens/pull/375

**Pull request closed without merging**
