### PR TITLE
Create 0xcc6FC957872DaCd913B272f690E1cDD4A74624B1.json

### PR DESCRIPTION
**Pull request by seyicoded**
ADD AIT TOKEN

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
InvalidFileName: Filename must be the address + .json

**Comment by seyicoded** [comment]
file changed as required sir.

**Review by seyicoded — COMMENTED** [review]
yes it's changed except you meant in reference to another file

**Review by ligi — CHANGES_REQUESTED** [review]
the address does not seem to contain a contract: https://etherscan.io/address/0xcc6FC957872DaCd913B272f690E1cDD4A74624B1

**Pull request closed without merging**
