### PR TITLE
Added minds token

### PR DESCRIPTION
**Pull request by iamflorencejay**
Added the minds token. Details of this token are covered on minds.com/token

### CODE REVIEW

**Comment by iamflorencejay** [comment]
checking... everyone?

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

**Comment by iamflorencejay** [comment]
@ligi I will do it later.

**Comment by iamflorencejay** [comment]
@ligi It says that address is already checksumed on my end

**Comment by iamflorencejay** [comment]
Screenshot_2021-06-18-10-34-11-241_com brave browser

**Comment by iamflorencejay** [comment]
ok now I get it

**Review by ligi — CHANGES_REQUESTED** [review]
Problem with tokens/eth/0xB26631c6dda06aD89B93C71400D25692de89c068.json: org.ethereum.lists.tokens.InvalidTokenException: decimals reported from contract (18) do not match decimals in json (2)

**Comment by iamflorencejay** [comment]
ok. decimals right? I'll check

**Comment by iamflorencejay** [comment]
@ligi no errors this time :/

**Review by ligi — APPROVED** [review]

**Pull request merged**
