### PR TITLE
Create 0xa5b399a76bbabef93d70255525c1d2bcc3701d0b.json

### PR DESCRIPTION
**Pull request by glosmatin**

### CODE REVIEW

**Comment by glosmatin** [comment]
thanks for feedback, but this token is ERC20, MyCrypto file system has changed?

**Comment by ligi** [comment]
the contract is ERC-20 but the address must be in ERC-55.

**Comment by glosmatin** [comment]
Please text detail what I need to do?

**Comment by ligi** [comment]
read: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md -> use it

**Comment by glosmatin** [comment]
thanks for supported 👍

**Pull request merged**
