### PR TITLE
Add the HEX ERC-20 token

### PR DESCRIPTION
**Pull request by sixcorners**
Hey uh.. why do other json files have way more fields than is described in the README? Should I add more stuff here?

### CODE REVIEW

**Comment by sixcorners** [comment]
k. what about the social media and stuff? should I just copy the dai one?

**Comment by sixcorners** [comment]
I'll change it in a while.

**Comment by ligi** [comment]
These fields are optional - appreciated when you add them - but not mandatory.

**Comment by sixcorners** [comment]
Ok. I copied the file from sia and used that as a template.

**Comment by sixcorners** [comment]
The readme says the logo must be a square. Does it have to be an exact square?

**Comment by ligi** [comment]
Yes the logo must be exactly square

**Comment by sixcorners** [comment]
Uh ok. Sorry that took so long heh. Had to look up an imagemagick command.
How is it now?

**Pull request merged**
