### PR TITLE
Update Utrust Token after tokenswap.

### PR DESCRIPTION
**Pull request by martinhoaragao**
Following the KuCoin hack, we have done a token swap which is described [here](https://medium.com/utrust/utrust-statement-and-next-steps-on-the-kucoin-hack-bd0ddedf9080?source=collection_home---4------0-----------------------).

This change is already reflected on [Etherscan](https://etherscan.io/token/0xdc9Ac3C20D1ed0B540dF9b1feDC10039Df13F99c). 

Took the change to add logo and update social media profiles.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please do not delete the old token - but deprecate it like this: https://github.com/ethereum-lists/tokens/blob/84ec42258a567685f373bf28bd0e07827c501104/tokens/eth/0xBEB9eF514a379B997e0798FDcC901Ee474B6D9A1.json#L33

**Comment by martinhoaragao** [comment]
Updated it @ligi. Does it cover it like so? And sorry for the delay!

**Review by ligi — APPROVED** [review]

**Comment by martinhoaragao** [comment]
Hey, @ligi since I can't merge as it is protected. Is there any estimation/process for this to happen?

**Comment by ligi** [comment]
Oh sorry - thought I merged already after the change - but only approved and did not merge - thanks for the ping

**Pull request merged**
