### PR TITLE
add: Smooth Love Potion (SLP) (#564)

### PR DESCRIPTION
**Pull request by ja0b**
Add the SLP token please
See: https://www.coingecko.com/en/coins/smooth-love-potion

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

**Comment by ja0b** [comment]
@ligi Thanks!! I'm seeing this message, does this means that I only have to change the type from ERC20 to ERC-55 ?

image

And with this other tool I'm seeing this:

image

**Comment by ligi** [comment]
In the screenshots the Addresses are ERC-55 - but in the PR they are not

**Comment by ja0b** [comment]
> In the screenshots the Addresses are ERC-55 - but in the PR they are not

@ligi  I've updated to address, do I need to update the "type" to ERC-55  too ?

**Comment by ligi** [comment]
no the type is erc-20 just the address encoding is erc-55
but currently the filename is not yet

**Pull request closed without merging**
