### PR TITLE
Create 0xEBd9D99A3982d547C5Bb4DB7E3b1F9F14b67Eb83.json

### PR DESCRIPTION
**Pull request by creativejace**
token update

### CODE REVIEW

**Comment by creativejace** [comment]
@dob @celeduc @bpierre @evertonfraga hello hope you're well.  Just want to ensure I've followed all of the necessary steps.  Not quite sure what's next and how to get my pull request validated.  Any help is greatly appreciated.

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

**Comment by creativejace** [comment]
> Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)
> 
> You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

Thank you for you help!  Submitted the changes you requested.

**Comment by creativejace** [comment]
> Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)
> 
> You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

@ligi Hope you're well.  I made the changes that you requested.  Is there anything else that you need from me?  Thank you so much for all of your help.

**Review by ligi — APPROVED** [review]

**Pull request merged**
