### PR TITLE
Add VinuChain Network & Vita Inu

### PR DESCRIPTION
**Pull request by ElemontCapital**

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
addresses must use ERC-55 checksum

**Comment by ElemontCapital** [comment]
> addresses must use ERC-55 checksum

Hi, made some changes please try again.

**Comment by ElemontCapital** [comment]
Hi, made some changes please try again. @ligi

**Comment by ElemontCapital** [comment]
Hi, made some changes please try again. @ligi

**Review by ligi — APPROVED** [review]

**Pull request merged**
