### PR TITLE
Add MTA and mUSD

### PR DESCRIPTION
**Pull request by dereksilva**
Adding mStable's existing tokens

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Problem with tokens/eth/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86.json: org.ethereum.lists.tokens.InvalidTokenException: decimals reported from contract (8) do not match decimals in json (18

**Comment by dereksilva** [comment]
> Problem with tokens/eth/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86.json: org.ethereum.lists.tokens.InvalidTokenException: decimals reported from contract (8) do not match decimals in json (18

i did not commit changes to this file, and it's not included in the pull request.

**Comment by ligi** [comment]
oh sorry - this is the error:

Problem with tokens/eth/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5.json: org.ethereum.lists.tokens.InvalidTokenException: symbol reported from contract (mUSD) do not match symbol in json (MUSD)

**Comment by dereksilva** [comment]
Thanks @ligi. I just corrected the symbol to show `mUSD`.

**Review by ligi — APPROVED** [review]

**Pull request merged**
