### PR TITLE
Added RUNE Token to Defaults

### PR DESCRIPTION
**Pull request by THORChainMike**
Contract address: 0xdee02d94be4929d26f67b64ada7acf1914007f10
Symbol: RUNE
Decimals: 18

### CODE REVIEW

**Comment by THORChainMike** [comment]
Hi, @ligi 
Added .JSON filetype.
Where do I find the ERC-55 address?

**Comment by THORChainMike** [comment]
Uploading the file added some extra tags, but now I think everything should be correct?

**Comment by ligi** [comment]
Thanks - now we golden!

**Comment by THORChainMike** [comment]
Thank you very much. GitHub is tricky sometimes, but an excellent tool!

**Pull request merged**
