### PR TITLE
Create 0x29a99c126596c0Dc96b02A88a9EAab44EcCf511e.json

### PR DESCRIPTION
**Pull request by cobaltlend**
Cobalt – A new way to borrow!
The Cobalt lending platform aims to bring together borrowers into a fair democratic voting community in order to get all size loans from micro loans to six-figure loans all without the over sight of a bank, completely governed by the community and therefor the community directly profits from its’ involvement. The current credit system is fundamentally flawed and the Cobalt platform corrects this by facilitating a community voted and approved lending program on the blockchain that is completely based off the merits of the project, never seeing race, color, or individuals background. The only criteria considered for the loans will be merit of project and collateral provided by the borrower, then the community will be left to decide on funding the proposal or rejecting it.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
This is not valid json - at least the opening { is missing

**Comment by cobaltlend** [comment]
we sent a message and believe it is now fixed, can you verify?


[horizontal bar]
Cobalt Lend
Cobaltlend.com, Blockchain Lending Platform
[Cobaltlend.com]
Cincinnati, Ohio
https://cobaltlend.com/
________________________________

**Comment by ligi** [comment]
the PR is still invalid

**Comment by cobaltlend** [comment]
sent another message and again i was informed the issue was corrected, can you verify?

[horizontal bar]
Cobalt Lend
Cobaltlend.com, Blockchain Lending Platform
[Cobaltlend.com]
Cincinnati, Ohio
https://cobaltlend.com/
________________________________

**Comment by ligi** [comment]
nope

Selection_257

**Review by micowen — APPROVED** [review]

**Pull request closed without merging**
