### PR TITLE
add new ella token / folder

### PR DESCRIPTION
**Pull request by tayvano**
from https://github.com/MyCryptoHQ/mycrypto.com/pull/52

Name: Ellaism Dev Pool Mining Token
Symbol: MINING
Address: 0x991e7fe4b05f2b3db1d788e705963f5d647b0044
Decimals: 18
Website: https://pool.ellaism.org See "MINING Token" section.
Customer Support Email: core@ellaism.org

### CODE REVIEW

**Comment by tayvano** [comment]
New folder as well, FYI

**Comment by ligi** [comment]
Thanks! the new folder is not a problem - but we enforce ERC-55 now: The address is not valid with ERC-55 checksum 0x991e7fe4b05f2b3db1d788e705963f5d647b0044 expected: 0x991e7Fe4b05f2b3db1D788e705963f5D647b0044

**Comment by tayvano** [comment]
Whoops. Updated now

**Comment by ligi** [comment]
hehe - unfortunately also in the filename - perhaps should write a script to do this - we humans are just to weak ^^-)

**Comment by tayvano** [comment]
Yahaha. That is what I get for doing shit while on the phone running out the door. Give me an hour 🤣

**Comment by ligi** [comment]
hehe now the .json is missing - but I wrote a script to automate this now - after master `./gradlew correctFileNames` replaces all filenames by the address-field.json for the files ^^-)

**Comment by ligi** [comment]
:+1:

**Pull request merged**
