### PR TITLE
Add Belifex ( BEFX ) Token

### PR DESCRIPTION
**Pull request by Belifex**

### CODE REVIEW

**Comment by Belifex** [comment]
0xB91C2a2b953D72f3EF890490669a0A41B0ADD5f7 you mean this way right Upper and Lowercase

**Comment by ligi** [comment]
yes - but this also applies to the filename

**Comment by ligi** [comment]
no worries - but the filename must end in .json

**Comment by Belifex** [comment]
hahahah

**Comment by Belifex** [comment]
beer and coding never good

**Pull request merged**
