### PR TITLE
Add Syscoin (SYSX) Token

### PR DESCRIPTION
**Pull request by LucidLunacy**

### CODE REVIEW

**Comment by LucidLunacy** [comment]
> Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

Done. Thank you!

**Review by ligi — CHANGES_REQUESTED** [review]
Sorry but the path is completely wrong now - somehow you have the etherscan URL in there

**Comment by LucidLunacy** [comment]
> Sorry but the path is completely wrong now - somehow you have the etherscan URL in there

Apologies. That should be it now.

**Review by ligi — CHANGES_REQUESTED** [review]
it's still not in the correct folder - must be in the folder for mainnet

**Pull request closed without merging**
