### PR TITLE
Create  0x83430Ad463C81A4e99F20b9621dD84F3F125f08A,.json

### PR DESCRIPTION
**Pull request by naziriteministry**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
There is no contract at 0x83430Ad463C81A4e99F20b9621dD84F3F125f08A on ethereum MainNet

**Comment by naziriteministry** [comment]
There is contract at 0x83430Ad463C81A4e99F20b9621dD84F3F125f08A on binance MainNet which change have being made awaiting approval.
thanks

**Comment by ligi** [comment]
don't change the type - but put the file in the correct folder

**Comment by naziriteministry** [comment]
can you guide me please.
thanks

**Comment by ligi** [comment]
it is now in the eth folder -eth is for ethereum mainnet - there should also be a folder for your chain

**Review by naziritenzc — CHANGES_REQUESTED** [review]
CHANGE TO BINANCE FOLDER

**Comment by ligi** [comment]
still in the eth folder

**Comment by naziritenzc** [comment]
PLEASE CAN YOU GIVE ME A GUIDE

**Comment by naziritenzc** [comment]
HELLO

**Review by ligi — CHANGES_REQUESTED** [review]
symbol reported from contract (NZC) do not match symbol in json (nzcC)

**Comment by naziriteministry** [comment]
SYMBOL CORRECTED

**Comment by naziriteministry** [comment]
PLEASE WHY IS CHECKS FAILING AFTER ALL CORRECTION DONE, PLEASE VERIFY

**Review by naziriteministry — COMMENTED** [review]
CHANGES MADE

**Comment by ligi** [comment]
it is in 2 chains

**Comment by naziriteministry** [comment]
it is reading workflow awaiting approval

**Comment by ligi** [comment]
I will not approve when it is obviously wrong

**Comment by naziriteministry** [comment]
> it is in 2 chains
ok

**Review by ligi — CHANGES_REQUESTED** [review]
symbol reported from contract (NZC) do not match symbol in json (nzc)

**Review by naziriteministry — COMMENTED** [review]
#close this please on the erc chain

**Comment by naziriteministry** [comment]
please any issues

**Comment by ligi** [comment]
symbol reported from contract (NZC) do not match symbol in json (nzc)

**Comment by naziriteministry** [comment]
IT SHOWED CHECKED PASSED BUT MERGING IS BLOCKED

**Review by naziritenzc — APPROVED** [review]

**Comment by naziriteministry** [comment]
please merge pull request

**Comment by naziritenzc** [comment]
hello

**Review by julioAk47 — APPROVED** [review]

**Pull request merged**
