### PR TITLE
Add AUDIUS token

### PR DESCRIPTION
**Pull request by ExperiBass**
I think i got everything correct :3

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

**Comment by ExperiBass** [comment]
Ok so i did miss something, lemmie get that for you uwu

**Comment by ExperiBass** [comment]
wait, the sites telling me its already been checksummed? i get this output in the console

```
0x18aaa7115705e8be94bffebde57af9bfc265b998
0x18aAA7115705e8be94bfFEBDE57Af9BFc265B998
```

**Comment by ligi** [comment]
in your PR it's all lowercase - so not checksummed:

**Comment by ExperiBass** [comment]
oHHHHHHHHHHHHHHH i see ok

**Comment by ExperiBass** [comment]
ok there we go

**Review by ligi — CHANGES_REQUESTED** [review]
Problem with tokens/eth/0x18aAA7115705e8be94bfFEBDE57Af9BFc265B998.json: org.ethereum.lists.tokens.InvalidTokenException: decimals reported from contract (18) do not match decimals in json (9)

**Comment by ExperiBass** [comment]
Ok I had a idea the decimals were off, what's a reliable source to get the decimals of a token?

**Comment by ligi** [comment]
it's 18

**Comment by ExperiBass** [comment]
I meant as in a site, the sites I looked at said the decimal was 9

**Comment by ligi** [comment]
the BlockChain is the source of truth here ;-)

**Comment by ExperiBass** [comment]
ok, we should be good now?

**Comment by ExperiBass** [comment]
Pog :D

**Pull request merged**
