### PR TITLE
add BEP20 TWT

### PR DESCRIPTION
**Pull request by zachzwei**
adding details for BEP20 TWT for Trezor support
https://community.trustwallet.com/t/twt-is-now-available-on-binance-smart-chain/72722/2

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
This address is not a contract. Also provide some blog post or something official about this token

**Comment by ligi** [comment]
cc @vikmeup

**Comment by vikmeup** [comment]
> This address is not a contract. Also provide some blog post or something official about this token

Token address: https://bscscan.com/address/0x4b0f1812e5df2a09796481ff14017e6005508003

**Comment by ligi** [comment]
ah so it is not on the ethereum chain? Then it must not be in the eth directory

**Comment by vikmeup** [comment]
> ah so it is not on the ethereum chain? Then it must not be in the eth directory

This make sense. @zachzwei can you move this info into `smartchain` directory (need to create it)

**Comment by ligi** [comment]
better call in bnb to be en par with https://github.com/ethereum-lists/chains/blob/master/_data/chains/56.json#L27

**Pull request closed without merging**
