### PR TITLE
Add Token

### PR DESCRIPTION
**Pull request by engenie**
Please include into Fether the following Token:
GermanCoin
GCX
Contract: 
0x44A67C8570a61A28bAfd0035042f2F0A73a64428
Decimals: 6

### CODE REVIEW

**Comment by engenie** [comment]
Hi @ligi,
Thx to remind me, will try to do next time, I am not that familiar with
this system.

Regards
Dipl.- Ing. Schenol Sen
Schützenstr. 2
64521 Groß-Gerau
Mobil.: 0175-1626795

ligi <notifications@github.com> schrieb am Di., 23. Apr. 2019, 02:47:

**Comment by engenie** [comment]
Hi, Is the GCX Token now included in Fether? please would you confirm, thx much!

**Comment by ligi** [comment]
did you submit an updated PR?

**Comment by engenie** [comment]
No

**Comment by ligi** [comment]
I guess this is also the answer to your question then ;-)

**Comment by engenie** [comment]
It is necessary?

**Comment by ligi** [comment]
yes

**Comment by engenie** [comment]
How should the pr be to include the GCX Token to Fether?

**Comment by ligi** [comment]
there is information in the README - or look how the other tokens did it

**Comment by engenie** [comment]
Can you give me please an example link

**Comment by engenie** [comment]
Thx

**Comment by engenie** [comment]
Thx

**Comment by ligi** [comment]
sorry - but no. If you can't figure this out you should better stop what you are doing - also just skimmed your "whitepaper" and still shaking my head ..

**Comment by engenie** [comment]
Why so unfriendly, just asked for suppprt, :cry:

**Comment by ligi** [comment]
I am happy to give support to viable projects that show some self-initiative - seeing none of this here ..

**Comment by ligi** [comment]
also think the whole project is trolling - that can't possibly be serious

**Comment by engenie** [comment]
Ligi, the project  serious and we try our best for the moment, will send new pr.

**Comment by ligi** [comment]
OK - if the PR is valid I will merge it - still can't believe this is serious and either scam or trolling - but this will not be a blocker for merging ..

**Comment by engenie** [comment]
Hello Ligi, I did a new pr, can you check pls.

**Pull request closed without merging**
