### PR TITLE
Added new Uniswap V2 pair tokens

### PR DESCRIPTION
**Pull request by bowensanders**
This adds the new Uniswap V2 pair tokens of the highest trade volume and highest liqiudities, as of this last 7 days. There are 109 new entries.

### CODE REVIEW

**Comment by bowensanders** [comment]
As per the advice from @blurpesec I have added `"invalid_erc20_symbol": true,` to the files, as each token needs a valid, descriptive name rather than all 109 tokens reporting as (UNI-V2) which provides little useful information. 

I have not yet used gradle, so running the test scripts myself is going to require some instruction. However, in the case of these files, they are all based on a template, and only the names and addresses change, so there should be very few, if any more, iterations of fixes on this project (fingers crossed)

**Comment by ligi** [comment]
Great! Yes makes sense - and CI is happy after the change

**Comment by bowensanders** [comment]
Thank you so much!

**Comment by bowensanders** [comment]
This closes [ch6256]

**Pull request merged**
