### PR TITLE
Added new Melonport token - Renamed old one.

### PR DESCRIPTION
**Pull request by blurpesec**
This is an alternative to #185.

### Changes:
* Edits old MLN token to indicate it's old.
* Adds a new MLN token object.

From other PR: 
> https://medium.com/melonport-blog/mln-token-migration-event-96b1c8003876

> Needs update for Friday, Feb 1, 2019: Update to reference the MLN token address the new one

### CODE REVIEW

**Comment by ligi** [comment]
Thanks! But we should add a deprecation block here like: 5c3f6a71

**Comment by blurpesec** [comment]
Hey @ligi. I noticed that [this](https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/TokenChecker.kt) doesn't yet support `migration_type` other than `auto` yet. But this one is a manual process. Would you like me to just add it as `auto`?

**Comment by blurpesec** [comment]
That works :)

**Comment by ligi** [comment]
great - will hit master in 5min

**Comment by ligi** [comment]
@blurpesec this migration type is available now

**Comment by blurpesec** [comment]
@ligi Does this ^ look alright?

**Comment by ligi** [comment]
yes - looks good - just not yet sure about the added (old) (new) - but we can leave it that way for now. But thought more that this could be added on the edge then (would also allow for localisation then, 
Can you rebase your branch to master so I can make the CI happy? Otherwise it does not let me merge currently

**Pull request merged**
