### PR TITLE
Create 0xC39E626A04C5971D770e319760D7926502975e47.json

### PR DESCRIPTION
**Pull request by jmaxwell2000**
AXPR replaces AXP: https://twitter.com/aXpire_official/status/1017442224978710529

### CODE REVIEW

**Comment by ligi** [comment]
:+1: 
do you want to close #126 then?

**Comment by jmaxwell2000** [comment]
Yes, that would be great. I apologize, I am new to github, Im not on the
dev team, so this process is a little confusing to me.

**Comment by ligi** [comment]
I closed it - No worries everything worked out in the end ;-)

**Comment by ligi** [comment]
depends on the release-cycle of the consuming project

**Pull request merged**
