### PR TITLE
Create 0x44A67C8570a61A28bAfd0035042f2F0A73a64428.json

### PR DESCRIPTION
**Pull request by engenie**
See  https://www.germancoin.info 

Token tracker:  https://etherscan.io/token/0x44a67c8570a61a28bafd0035042f2f0a73a64428

### CODE REVIEW

**Comment by engenie** [comment]
THX alot!

**Comment by ligi** [comment]
you are welcome - but also note that this is not endorsement in any way or form. I will merge any coin that fulfills formal criteria - I still have the feeling this coin is either scam or trolling

**Comment by engenie** [comment]
Hello Ligi, your feeling is not correct, this project is a serious one, we are just at the beginning, cheers!

**Comment by ligi** [comment]
time will tell - I will look back at the project in a year and see If I was right or wrong ..-)

**Comment by engenie** [comment]
Hi Ligi, when will be the Token included in Fether? In the release from today it is not in.

**Comment by ligi** [comment]
you will need to ask the Fether team ..

**Pull request merged**
