### PR TITLE
Added DoBETacceptBET Token to Defaults

### PR DESCRIPTION
**Pull request by dobetacceptbet**

### CODE REVIEW

**Comment by ligi** [comment]
I see you pushed an update - but the file still needs to be a json file

**Comment by dobetacceptbet** [comment]
Could you clarify which file you are talking about? I filled in the array all the data. Thank you


>Вторник, 20 марта 2018, 12:10 +03:00 от ligi <notifications@github.com>:
>
>I see you pushed an update - but the file still needs to be a json file
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Дмитрий Шихалев
+79654751385
www.dobetacceptbet.com

**Comment by ligi** [comment]
sure thing - the file you added is named tokens/eth/0x386Faa4703a34a7Fdb19Bec2e14Fd427C9638416
but it needs to be tokens/eth/0x386Faa4703a34a7Fdb19Bec2e14Fd427C9638416.json

**Comment by ligi** [comment]
closing this now for inactivity - feel free to reopen when you are ready

**Pull request closed without merging**
