### PR TITLE
Adding ERC-20 tokens on Avalanche network

### PR DESCRIPTION
**Pull request by jpop32**
Added Avalanche networl and AVAX and USDT ERC-20s on it

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

**Comment by ligi** [comment]
also as this are the first tokens on the network you need to add this mapping:

https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/Main.kt#L12

**Comment by jpop32** [comment]
> Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

Hm. According to the tool, both addresses already are ERC-55 compliant. Am I missing something?

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
sorry - the CI error was rooted in the missing mapping - looked like a ERC55 error to me on the first glance

**Comment by jpop32** [comment]
Hi there. This PR was merged a couple of weeks ago, but Avalanche network is still not available on https://mycrypto.com/. Tried connecting with Metamask and Ledger Nano, wasn't available. Is there anything else that needs to be done? Can I help?

**Pull request merged**
