### PR TITLE
rif token on rsk mainnet

### PR DESCRIPTION
**Pull request by alebanzas**
Implements [EIP-1191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md) for checksum, extending [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md)

### CODE REVIEW

**Comment by ligi** [comment]
seems related: https://github.com/komputing/KEthereum/issues/80

**Comment by jonathansmirnoff** [comment]
@ligi because of the PR: https://github.com/komputing/KEthereum/pull/85 was merged, I wanted to know how we can forward with this PR. Do I have to add the chainId? Thanks!

**Comment by ligi** [comment]
we have the chainId here: https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/Main.kt#L13 no need to put it in the json.
What needs to happen: add a new field address_eip1191 in the CI scripts / README. We cannot directly change the behavior of the address field as upstream projects might stumble over it. 
I will merge PRs implementing this - but I will not do them as I think EIP1191 is a horrible idea actualy.

**Comment by jonathansmirnoff** [comment]
Thanks for your response and I understand that you don't like the EIP1191. 
I need more clarification about the steps that I should do:
- Add RSK chainId here: https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/Main.kt#L13 
- Update CI Script: Should I update this file https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/TokenChecker.kt?

**Comment by ligi** [comment]
> * Add RSK chainId here: https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/Main.kt#L13

as far as I see it is already there

> * Update CI Script: Should I update this file https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/TokenChecker.kt?

yes

**Comment by jonathansmirnoff** [comment]
@ligi because the PR https://github.com/ethereum-lists/tokens/pull/339 has been merged, do you think this PR can be merged? Thanks!

**Comment by ligi** [comment]
sure - can you rebase to master?

**Comment by jonathansmirnoff** [comment]
> sure - can you rebase to master?

Sure, I'll try to do it. If I can't do it because I didn't make this PR, I'll make another PR and ask to close this.

**Comment by jonathansmirnoff** [comment]
Done! :)

**Comment by ligi** [comment]
merged ;-)

**Comment by jonathansmirnoff** [comment]
Thanks so much for your help in this process!

**Pull request merged**
