### PR TITLE
move tokens

### PR DESCRIPTION
**Pull request by alexvandesande**
someone had added them to root

### CODE REVIEW

**Comment by 409H** [comment]
lgtm!

**Comment by alexvandesande** [comment]
Also noticed there were two tokens in the same file. Some sloppy add!

**Comment by ligi** [comment]
Yea - usually the CI picks up these mistakes and I just have to check decimals and the website - but as the tokens where in the wrong directory the CI did not pick them up - should not happen again after #80 - now the last thing is the missing .json extension on one of the files ..-)

**Comment by ligi** [comment]
@alexvandesande thanks so much!

**Pull request merged**
