### PR TITLE
Create csimaz

### PR DESCRIPTION
**Pull request by csimaz**

### CODE REVIEW

**Review by csimaz — COMMENTED** [review]
ERC20 TO ERC55 FOR TREZOR

**Review by ligi — CHANGES_REQUESTED** [review]
This is wrong on so many levels - I do not even know where to start ..
Please look at the other tokens and read the readme

**Review by csimaz — COMMENTED** [review]
TRUMPWON

**Comment by csimaz** [comment]
Trumpwon

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request closed without merging**
