### PR TITLE
feat: add PATH token to defaults

### PR DESCRIPTION
**Pull request by Shrugs**
https://path.network

### CODE REVIEW

**Comment by Shrugs** [comment]
Ah! The sample JSON on https://support.mycrypto.com/tokens/token-creators-add-your-token-to-mycrypto.html indicates a string key for decimals. I've updated this PRPR to use a number for decimals and use an ERC55 address.

**Comment by ligi** [comment]
@Shrugs thanks - looks better now - the only thing missing to make the CI happening is that the file ends in .json

@tayvano @409H can we change the sample json there to not confuse users?

**Comment by tayvano** [comment]
Of course. I'll get it updated today @ligi 

Thanks @Shrugs for catching that!

**Comment by Shrugs** [comment]
Looks like PATH is actually in the repo now after the most recent import from MEW: https://github.com/ethereum-lists/tokens/blob/master/tokens/eth/0xF813F3902bBc00A6DCe378634d3B79D84F9803d7.json

closing since there are no more changes to be made. thanks for your patience!

**Pull request closed without merging**
