### PR TITLE
Create 0xC48b4814fAEd1CCc885DD6fDe62A6474AeCbb19a.json

### PR DESCRIPTION
**Pull request by MrLightspeed**
Add CMERGE Token

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
social has unknown fields - the currently allowed ones are to be found here:
https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/model/Social.kt
I could add tiktok - but the other one not really

**Review by MrLightspeed — COMMENTED** [review]
Corrected Socials

**Comment by ligi** [comment]
please rebase to master - master now supports tiktok

**Comment by MrLightspeed** [comment]
> 

Was this meant for me to perform?

**Comment by ligi** [comment]
yes

**Comment by MrLightspeed** [comment]
> yes

Are you willing to explain how in the github.com interface? Sorry for the troubles.

**Comment by ligi** [comment]
maybe the easiest is you create a new PR

**Comment by MrLightspeed** [comment]
Ok I did that and thank you for your patience.

**Pull request closed without merging**
