### PR TITLE
Create 0x75231f58b43240c9718dd58b4967c5114342a86c.json

### PR DESCRIPTION
**Pull request by youziXJJ**
okb contract

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

**Comment by youziXJJ** [comment]
> Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

Do I have to register in erc-55? Is there a related tutorial? We are OKB issuer, we can provide the source code, currently we have uploaded it to ethscan

**Comment by ligi** [comment]
please follow the provided links for details on ERC-55
also your image is invalid: https://etherscan.io/token/images/okb.png

**Review by youziXJJ — COMMENTED** [review]
update images link
I am not sure what I should do EIP-55

**Review by ligi — APPROVED** [review]

**Pull request merged**
