### PR TITLE
Create 0x0A680E503fd9ae14B62444C75ffB4BEf1F105666.json

### PR DESCRIPTION
**Pull request by dimabarsu**
Add Arma coin GZM token

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The json is placed in the wrong directory

**Comment by dimabarsu** [comment]
Where should i place my *.json file ? I followed this guide https://tokpie.io/blog/how-to-add-token-to-trezor-list

**Comment by ligi** [comment]
you can even see it in the tutorial - or just look where the others are ;-)

**Comment by dimabarsu** [comment]
Is the path "ethereum-lists/tokens/tokens/eth/your_token_address.json" correct?

**Comment by dimabarsu** [comment]
Which branch should I choose to create file in?

**Pull request closed without merging**
