### PR TITLE
令牌/eth/0x5569bcb32aade71bf6a72d12698d3c710c7587e4.json

### PR DESCRIPTION
**Pull request by Jack63520**
{ 
   "symbol": "TIME", 
   "invalid_erc20_symbol": true, 
   "name": "Time Token", 
   "type": "ERC20", 
   "address": "0x5569bcb32aade71bf6a72d12698d3c710c7587e4", 
   "ens_address": "", 
   "decimals": 10, 
   "website": "http://www.tempusfund.io", 
   "logo": { 
   "src": "http://www-x-tempusfund-x-io.img.abc188.com/public/assets/static/images/logo.jpg", 
   "width": "", 
   "height": "", 
   "ipfs_hash": "" 
   }, 
   "support": { 
   "email": "service@tempusfund.io", 
   "url": "" 
   }, 
   "social": { 
   "blog": "", 
   "chat": "Time66HOME", 
   "facebook": "", 
   "forum": "", 
   "github": "", 
   "gitter": "", 
   "instagram": "", 
   "linkedin": "", 
   "reddit": "", 
   "slack": "", 
   "telegram": "", 
   "twitter": "https://twitter.com/TIMEFOUNDATION_", 
   "youtube": "" 
   } 
  }

### CODE REVIEW

**Comment by ligi** [comment]
This PR does not really make sense to me -  please reopen proper when this was no automated spam

**Comment by Jack63520** [comment]
> 此PR对我而言真的没有意义-如果这不是自动垃圾邮件，请重新打开

I want to submit my token, I don’t know if it’s submitted here

**Comment by Jack63520** [comment]
> This PR does not really make sense to me - please reopen proper when this was no automated spam
I want to submit my token, I don’t know if it’s submitted here

**Comment by Jack63520** [comment]
> This PR does not really make sense to me - please reopen proper when this was no automated spam

TIME TOKEN is the link system of TIME ecology. It is the ecological consensus who exercises ecological rights and enjoys lifeThe smart contract certificate of the state value.
In order to implement the core idea of POW more fairly, TIME adopts a one-chain dual-certificate system(TIME&TimeF), equal incentives for every contribution. The first round of incentives is in the form of ETH Token, after the main chain goes onlinePerform mapping switch.
TIME Pass will cover the entire industry chain of wallets, exchanges, finance, games, and shopping malls in the future; the first IGOMode, the practical significance of the “smart contract certificate” of the landing pass, to ensure that each pass has a consensus assetGuaranteed!

**Comment by ligi** [comment]
ok - but then submit this token as a PR with the json not as text in the PR

**Pull request closed without merging**
