### PR TITLE
Add Walker 

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the address in tokens/eth/0xD64DeEA5F24934E3A1aa752912aEe8ffD8300C3F.json does not match the FileName

**Comment by samisbakedham** [comment]
> the address in tokens/eth/0xD64DeEA5F24934E3A1aa752912aEe8ffD8300C3F.json does not match the FileName

Fixed, thanks!

**Comment by samisbakedham** [comment]
[Build](https://github.com/ethereum-lists/tokens/actions/workflows/build_and_deploy.yml)

**Comment by samisbakedham** [comment]
> the address in tokens/eth/0xD64DeEA5F24934E3A1aa752912aEe8ffD8300C3F.json does not match the FileName
[Build](https://github.com/ethereum-lists/tokens/actions/workflows/build_and_deploy.yml)

**Comment by samisbakedham** [comment]
> Member

I was very tired, apologies and good catch! Thank you :)

**Comment by samisbakedham** [comment]
> the address in tokens/eth/0xD64DeEA5F24934E3A1aa752912aEe8ffD8300C3F.json does not match the FileName

Should be fixed now

**Comment by samisbakedham** [comment]
Should be A-OK

**Pull request merged**
