### PR TITLE
Update LRC token address

### PR DESCRIPTION
**Pull request by nickmccurdy**
This was migrated from https://github.com/MyCryptoHQ/MyCrypto/pull/2568.

Thanks @dong77!

### CODE REVIEW

**Comment by nickmccurdy** [comment]
@ligi I’d appreciate a review, we’re waiting on this to fix our LRC support

**Comment by nickmccurdy** [comment]
Thanks, should I just add a deprecation section to the existing file or does it need a second file like with TUSD (Old) and TUSD?

**Comment by ligi** [comment]
you add this to the old file and then add the new token to a new file

**Comment by nickmccurdy** [comment]
Thanks for your help, I added back the old LRC token file with the ` (old)` suffix and the depreciation section.

**Comment by ligi** [comment]
:+1:

**Pull request merged**
