### PR TITLE
Create 0x3D371413dd5489F3A04C07c0C2CE369c20986ceb.json

### PR DESCRIPTION
**Pull request by Vasilii79**
Add YOUC token

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

**Comment by Vasilii79** [comment]
> ERC-55

Could you please give me a link to the example where the address is in ERC-55 (filename and address field)?

**Comment by ligi** [comment]
All tokens are in ERC55 - the CI enforces is - pick any from here:
https://github.com/ethereum-lists/tokens/tree/master/tokens/eth

**Comment by Vasilii79** [comment]
> All tokens are in ERC55 - the CI enforces is - pick any from here:
So, instead of "Create 0x3d371413dd5489f3a04c07c0c2ce369c20986ceb.json", the file name must be "0x3d371413dd5489f3a04c07c0c2ce369c20986ceb.json" _  is that my mistake?

**Comment by ligi** [comment]
http://letmegooglethat.com/?q=ERC-55+ethereum

**Comment by Vasilii79** [comment]
> All tokens are in ERC55 - the CI enforces is - pick any from here:
> https://github.com/ethereum-lists/tokens/tree/master/tokens/eth

Could you pls clarify what change should be made now?
Will the logo be visible if I delete a line with "ipfs_hash"?

**Comment by Vasilii79** [comment]
> http://letmegooglethat.com/?q=ERC-55+ethereum

Hello, could you please just tell me what line in the .json file requires a change (must be fixed by me)?

**Comment by ligi** [comment]
line 3 needs change - the address must be provided in ERC-55

**Comment by ligi** [comment]
the field is not ERC-55 - the filename is still wrong

**Comment by Vasilii79** [comment]
> the field is not ERC-55 - the filename is still wrong

sorry, the fille name was updated too

**Comment by ligi** [comment]
The filename is still wrong - you updated the title:

Selection_285

**Comment by Vasilii79** [comment]
> > the field is not ERC-55 - the filename is still wrong
> 
> sorry, the file name has been just updated too

updated now

**Comment by Vasilii79** [comment]
> The filename is still wrong - you updated the title:
> 
> Selection_285

Many Thanks, Ligi! Kindly inform how long will it take to get the token visible in the list of coins supported by Trezor?

**Comment by ligi** [comment]
I cant say - guess with the next release. @matejcik might be able to provide more info

**Pull request merged**
