### PR TITLE
Add new token - Eristica (ERT)

### PR DESCRIPTION
**Pull request by ProHronus**
Already added in MEW

### CODE REVIEW

**Comment by ligi** [comment]
:+1:

**Comment by ProHronus** [comment]
Thanks for fast approve. What approximate time for updates to go live?

**Comment by ligi** [comment]
That depends on the release cycle of the consuming projects

**Comment by ProHronus** [comment]
For mycrypto.com?

**Comment by ligi** [comment]
I do not know - you will need to ask them

**Comment by ProHronus** [comment]
Sorry. I thought you are involved in this project too. WallETH and MyCrypto

**Pull request merged**
