### PR TITLE
Create 0xe6D2a9fCD946E07826C6cdd919DA04763eA4D812.json

### PR DESCRIPTION
**Pull request by bruhtokeno**
Add BRUH token

### CODE REVIEW

**Comment by bruhtokeno** [comment]
Hi,was Bruh rejected from the listing?

**Review by ligi — CHANGES_REQUESTED** [review]
Please put the file in the correct folder

**Comment by bruhtokeno** [comment]
What folder?

**Comment by ligi** [comment]
where the others are ;-)

**Comment by bruhtokeno** [comment]
Hi, I created a pull request to merge into the folder where the other Ethereum Tokens are

**Comment by bruhtokeno** [comment]
I can't move this file to the ETH tokens list. So Bruh was accepted?

**Comment by bruhtokeno** [comment]
@ligi Hi, how can I move it into the Ethereum tokens folder? I was redirected to a make pull request page that made me make the same pull request.

**Comment by ligi** [comment]
replaced by #608 - btw. SafeMath is not doing what you think it does ;-)

**Comment by bruhtokeno** [comment]
Thanks for the reminder :)

**Pull request closed without merging**
