### PR TITLE
Create 0x8Fb1a59cA2d57B51e5971A85277EFe72c4492983.json

### PR DESCRIPTION
**Pull request by daftoken**
I saw it failed on social id.  Removed ID

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
This is not a contract but an EOA

**Comment by daftoken** [comment]
Ligi,

Can you please just do this for me?  I keep failing and this error is
bogus. The decimals are 6.  I am guessing this does not check BSC contracts
only eth?

https://bscscan.com/token/0x8fb1a59ca2d57b51e5971a85277efe72c4492983

**Comment by ligi** [comment]
no sorry

**Comment by daftoken** [comment]
Ok well can you tell why the error is a decimal mismatch?   It is 6
decimals

**Comment by ligi** [comment]
because you did not put it in bsc

**Review by daftoken — COMMENTED** [review]
Their is no bsc folder.   ??

**Comment by ligi** [comment]
yea - bsc is not yet supported - so far no one was interested in supporting this weird chain

**Pull request closed without merging**
