### PR TITLE
Create 0x9Af5A20AaC8D83230ba68542Ba29d132d50cbe08.json

### PR DESCRIPTION
**Pull request by AntoineMarsan**

### CODE REVIEW

**Review by ligi — COMMENTED** [review]
this json file is placed in the wrong directory

**Review by ligi — CHANGES_REQUESTED** [review]
this json file is placed in the wrong directory

**Comment by AntoineMarsan** [comment]
> this json file is placed in the wrong directory

Could you please specify what directory to place the json file please? Thank you

**Comment by ligi** [comment]
if your token is on ETH mainnet - in tokens/eth

**Comment by AntoineMarsan** [comment]
> if your token is on ETH mainnet - in tokens/eth

Awesome, Thanks!

**Comment by AntoineMarsan** [comment]
> if your token is on ETH mainnet - in tokens/eth

New Pull Request created, please see #537

**Pull request closed without merging**
