### PR TITLE
Create 0xAAC111447138F8E44463b526875e762Fbf1c504F

### PR DESCRIPTION
**Pull request by AlzheimerChain**
Hello Guys, I am very new to this and not very technical type... I would like to add our ALZ token to the list. Please let me know if I have to something else or correct something.
Thank you very much!
Julia

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
You need to place it in the correct directory (tokens/eth) and the file must end with '.json'

**Comment by ligi** [comment]
got a bit better - but still not in the correct directory. it'S now in eth - but needs to be in tokens/eth

also the logo section is wrong - please look at the other tokens to see how it should look like - but this is not valid:

Selection_400

**Comment by AlzheimerChain** [comment]
Hello Ligi, is it better now?

**Comment by ligi** [comment]
no - I actually don't see any change since my review

**Comment by AlzheimerChain** [comment]
hm, i had my fried helped, the change should be in the file

**Pull request closed without merging**
