### PR TITLE
Added Uniswap exchange tokens

### PR DESCRIPTION
**Pull request by blurpesec**
These are some of the uniswap exchange tokens. These are the tokens used to watch an individual's pool balance and share

### CODE REVIEW

**Comment by blurpesec** [comment]
@ligi not sure why this is failing CI. any ideas?

**Comment by ligi** [comment]
Yea - I added some on-chain checks (mainly for the huge defi PR) and at least one of these contracts does not seem to be ERC-20 compliant.
There are options to work around this you can add invalid_erc20_decimals or invalid_erc20_symbol fields with the value true to the token.
Unfortunately the error message is not nice currently. Wanted to improve this but currently trapped in other tasks. Can you run the script locally?

**Comment by blurpesec** [comment]
> Yea - I added some on-chain checks (mainly for the huge defi PR) and at least one of these contracts does not seem to be ERC-20 compliant.
> There are options to work around this you can add invalid_erc20_decimals or invalid_erc20_symbol fields with the value true to the token.
> Unfortunately the error message is not nice currently. Wanted to improve this but currently trapped in other tasks. Can you run the script locally?

Do you have some docs somewhere i can use to reference on how to do this?

**Comment by blurpesec** [comment]
> Yea - I added some on-chain checks (mainly for the huge defi PR) and at least one of these contracts does not seem to be ERC-20 compliant.
> There are options to work around this you can add invalid_erc20_decimals or invalid_erc20_symbol fields with the value true to the token.

Oh. I think all of these tokens are going to fail. They all have their decimals value in unit256 instead of uint8. And since they're generated from a factory, all of them are going to be that way D: . ill add them all to the exclusion list.

**Comment by blurpesec** [comment]
Hiya @ligi anything else i need to do for this? :-)

**Comment by ligi** [comment]
:+1:

**Pull request merged**
